language: cpp
before_script:
- sudo apt-get install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt-get install libspdlog-dev -y
script:
- cmake .
- cmake --build . -- VERBOSE=1
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: $TRAVIS_BRANCH
  script:
  - curl -T print_ip-$TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER-Linux.deb -uandreyc2018:$BINTRAY_API_KEY "https://api.bintray.com/content/andreyc2018/otus-cpp/print_ip/$TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER/print_ip-$TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_DOCS_KEY
  on:
    branch: $TRAVIS_BRANCH

